---
- name: Firewall open http and https ports
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http
    - https

- name: Install packages
  include_tasks: install.yml

- name: Ensure httpd_can_network_connect is set to 1
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Ensure there is log directory
  file:
    path: /var/log/nginx
    state: directory

- name: Check if the nginx.conf managed by ansible
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "^## Managed by Ansible"
    state: absent
  check_mode: yes
  register: nginx_managed
  changed_when: not nginx_managed.changed

- name: Ensure nginx is configured
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf 
  when: nginx_managed.changed

- name: Ensure SSL certificate is obtained
  command: >
    certbot --nginx 
    -d {{ domain }} -d www.{{ domain }} -d jenkins.{{ domain }}
    --non-interactive --agree-tos --email {{ email }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}
  notify: reload nginx

- name: Create post renewal hook
  copy:
    dest: /etc/letsencrypt/renewal-hooks/post/nginx-reload.sh
    content: |
      #!/bin/sh
      systemctl reload nginx
    mode: '0755'

- name: Enable SSL renewal
  service:
    name: certbot-renew.timer
    state: started
    enabled: yes
