---
- name: Ensure firewall is enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open http and https ports
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http
    - https

- name: Install rpm signature key for EPEL
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    state: present

- name: Install EPEL repo
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: Install nginx and certbot
  package: 
    name: 
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Check if the nginx.conf managed by ansible
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "^## Managed by Ansible"
    state: absent
  check_mode: yes
  register: nginx_check

- name: Set nginx_managed fact
  set_fact:
    nginx_managed: "{{ nginx_check.changed }}"

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf 
  when: not nginx_managed

- name: Obtain SSL certificate
  command: >
    certbot --nginx 
    -d {{ domain }} -d www.{{ domain }}
    --non-interactive --agree-tos --email {{ email }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}
  notify: reload nginx

- name: Create post renewal hook
  copy:
    dest: /etc/letsencrypt/renewal-hooks/post/nginx-reload.sh
    content: |
      #!/bin/sh
      systemctl reload nginx
    mode: '0755'

- name: Enable SSL renewal
  service:
    name: certbot-renew.timer
    state: started
    enabled: yes
