---
- name: Setup services
  hosts: azure
  become: yes

  vars:
    domain: ky3ow.xyz
    email: vova2341591@gmail.com
    java_packages:
      - java-17-openjdk
    jenkins_plugins:
      - git
      - workflow-aggregator
      - docker-workflow
      - configuration-as-code

  roles: 
    - role: prerequisites
      tags: prerequisites_tag
    - role: docker
      tags: docker_tag
    - role: nginx
      tags: nginx_tag
    - role: geerlingguy.java
      tags: java_tag
    - role: geerlingguy.jenkins
      tags: jenkins_tag
    - role: configure-jenkins
      tags: configure_jenkins_tag
